// AuthBackend_PC.cpp -- Microsoft/Mojang login transport for the desktop.
//
// Mbed TLS (external/mbedtls, Apache-2.0, pinned submodule -- see
// .gitmodules) speaking HTTP/1.1 over mbedtls_net sockets: no dependency on
// whatever TLS the host happens to ship, and the same library family the
// 3DS portlibs' curl is built on. The Mozilla CA bundle
// (resources/cacert.pem, MPL-2.0) is compiled into the binary
// (generated/PcCaBundle.cpp from resources/PcCaBundle.cpp.in) and both the
// chain and the host name are verified -- this channel carries account
// tokens.
//
// The desktop target always wires the transport (Mbed TLS + the embedded CA
// bundle), so this file always builds the real channel; the login UI itself
// stays hidden until a client id is configured (see OPTICRAFT_MSA_CLIENT_ID).

#include "platform/PlatformAuth.h"
#include "platform/PlatformConfig.h"

#if PLATFORM_MSAUTH

#include <mbedtls/ctr_drbg.h>
#include <mbedtls/entropy.h>
#include <mbedtls/error.h>
#include <mbedtls/net_sockets.h>
#include <mbedtls/ssl.h>
#include <mbedtls/version.h>
#include <mbedtls/x509_crt.h>

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <string>
#include <vector>

#include "platform/Log.h"

// Generated by CMake from resources/cacert.pem (see CMakeLists.txt).
extern "C" const char opticraft_ca_bundle_pem[];

namespace
{
constexpr std::size_t kMaxResponseBytes = 1024 * 1024;
constexpr uint32_t kReadTimeoutMs = 30000;
constexpr const char *kUserAgent = "OptiCraft-Heritage/PC";

struct UrlParts
{
	std::string host;
	std::string port;
	std::string path;
};

bool parseHttpsUrl(const std::string &url, UrlParts &out)
{
	const std::string scheme = "https://";
	if (url.compare(0, scheme.size(), scheme) != 0)
		return false;
	const std::size_t authorityStart = scheme.size();
	const std::size_t pathStart = url.find('/', authorityStart);
	const std::string authority = pathStart == std::string::npos
		? url.substr(authorityStart)
		: url.substr(authorityStart, pathStart - authorityStart);
	if (authority.empty() || authority.find('[') != std::string::npos)
		return false; // the auth endpoints are plain DNS names
	out.path = pathStart == std::string::npos ? "/" : url.substr(pathStart);
	out.port = "443";
	const std::size_t colon = authority.find(':');
	if (colon != std::string::npos)
	{
		out.host = authority.substr(0, colon);
		out.port = authority.substr(colon + 1);
	}
	else
	{
		out.host = authority;
	}
	return !out.host.empty();
}

std::once_flag caOnce;
bool caOk = false;
mbedtls_x509_crt caBundle;

bool ensureCaBundle()
{
	std::call_once(caOnce, []
	{
		mbedtls_x509_crt_init(&caBundle);
		const std::size_t length = std::strlen(opticraft_ca_bundle_pem);
		// >= 0: the count of *failed* certs is tolerated; only a fatal
		// negative return means the bundle did not load at all.
		caOk = mbedtls_x509_crt_parse(&caBundle,
		                              reinterpret_cast<const unsigned char *>(opticraft_ca_bundle_pem),
		                              length + 1) >= 0;
		if (!caOk)
		{
			mbedtls_x509_crt_free(&caBundle);
			MC_LOG_ERROR("auth", "pc: the embedded CA bundle could not be parsed\n");
		}
	});
	return caOk;
}

void logTlsError(const char *what, int code)
{
	char buffer[256] = {0};
	mbedtls_strerror(code, buffer, sizeof buffer);
	MC_LOG_ERROR("auth", "pc: %s: %s (-0x%04x)\n", what, buffer, -code);
}

bool containsCaseInsensitive(const std::string &text, const char *needle)
{
	const std::size_t needleLength = std::strlen(needle);
	if (text.size() < needleLength)
		return false;
	for (std::size_t i = 0; i + needleLength <= text.size(); i++)
	{
		std::size_t j = 0;
		while (j < needleLength)
		{
			const char a = text[i + j];
			const char b = needle[j];
			const char lowerA = a >= 'A' && a <= 'Z' ? static_cast<char>(a - 'A' + 'a') : a;
			const char lowerB = b >= 'A' && b <= 'Z' ? static_cast<char>(b - 'A' + 'b') : b;
			if (lowerA != lowerB)
				break;
			j++;
		}
		if (j == needleLength)
			return true;
	}
	return false;
}

// HTTP/1.1 response parsing: status line + headers + body, with both
// Content-Length and chunked transfer decoding. Deliberately minimal --
// the login endpoints speak well-formed HTTP with small bodies.
bool parseHttpResponse(const std::string &raw, int &status, std::string &body)
{
	const std::size_t headerEnd = raw.find("\r\n\r\n");
	if (headerEnd == std::string::npos || raw.compare(0, 5, "HTTP/") != 0)
		return false;
	const std::string head = raw.substr(0, headerEnd);
	std::string rest = raw.substr(headerEnd + 4);

	const std::size_t space = head.find(' ');
	if (space == std::string::npos || space + 3 >= head.size())
		return false;
	status = std::atoi(head.c_str() + space + 1);
	if (status < 100 || status > 599)
		return false;

	if (containsCaseInsensitive(head, "transfer-encoding:") &&
	    containsCaseInsensitive(head, "chunked"))
	{
		body.clear();
		std::size_t position = 0;
		for (;;)
		{
			const std::size_t lineEnd = rest.find("\r\n", position);
			if (lineEnd == std::string::npos)
				return false;
			const std::string sizeText = rest.substr(position, lineEnd - position);
			char *endPtr = nullptr;
			const unsigned long long chunkSize = std::strtoull(sizeText.c_str(), &endPtr, 16);
			if (endPtr == nullptr || endPtr == sizeText.c_str() || chunkSize == 0)
				return chunkSize == 0; // the zero chunk is the real terminator
			if (body.size() + chunkSize > kMaxResponseBytes)
				return false;
			const std::size_t chunkStart = lineEnd + 2;
			if (chunkStart + chunkSize + 2 > rest.size())
				return false;
			body.append(rest, chunkStart, chunkSize);
			position = chunkStart + chunkSize + 2; // skip chunk + trailing CRLF
		}
	}

	// Content-Length or connection-close delimited (read loop stops at EOF).
	body = std::move(rest);
	return true;
}
} // namespace

bool PlatformAuth::microsoftLoginSupported()
{
	return true;
}

bool PlatformAuth::httpsRequest(const HttpRequest &request, HttpResponse &response)
{
	response = HttpResponse();
	UrlParts url;
	if (!parseHttpsUrl(request.url, url) || !ensureCaBundle())
		return false;

	mbedtls_net_context serverFd;
	mbedtls_ssl_context ssl;
	mbedtls_ssl_config conf;
	mbedtls_ctr_drbg_context drbg;
	mbedtls_entropy_context entropy;
	mbedtls_net_init(&serverFd);
	mbedtls_ssl_init(&ssl);
	mbedtls_ssl_config_init(&conf);
	mbedtls_ctr_drbg_init(&drbg);
	mbedtls_entropy_init(&entropy);

	// RAII teardown for the whole TLS pile.
	struct Cleanup
	{
		mbedtls_net_context *fd;
		mbedtls_ssl_context *ssl;
		mbedtls_ssl_config *conf;
		mbedtls_ctr_drbg_context *drbg;
		mbedtls_entropy_context *entropy;
		~Cleanup()
		{
			mbedtls_net_free(fd);
			mbedtls_ssl_free(ssl);
			mbedtls_ssl_config_free(conf);
			mbedtls_ctr_drbg_free(drbg);
			mbedtls_entropy_free(entropy);
		}
	} cleanup{&serverFd, &ssl, &conf, &drbg, &entropy};

	const char *personalization = "opticraft-msauth";
	int rc = mbedtls_ctr_drbg_seed(&drbg, mbedtls_entropy_func, &entropy,
	                               reinterpret_cast<const unsigned char *>(personalization),
	                               std::strlen(personalization));
	if (rc != 0)
	{
		logTlsError("drbg seed failed", rc);
		return false;
	}
	if ((rc = mbedtls_ssl_config_defaults(&conf, MBEDTLS_SSL_IS_CLIENT,
	                                      MBEDTLS_SSL_TRANSPORT_STREAM,
	                                      MBEDTLS_SSL_PRESET_DEFAULT)) != 0)
	{
		logTlsError("ssl config failed", rc);
		return false;
	}
	// Mbed TLS 3.x returns void here (it was int in 2.x).
	mbedtls_ssl_conf_ca_chain(&conf, &caBundle, nullptr);
	mbedtls_ssl_conf_authmode(&conf, MBEDTLS_SSL_VERIFY_REQUIRED);
	mbedtls_ssl_conf_rng(&conf, mbedtls_ctr_drbg_random, &drbg);
	mbedtls_ssl_conf_read_timeout(&conf, kReadTimeoutMs);

	if ((rc = mbedtls_ssl_setup(&ssl, &conf)) != 0 ||
	    (rc = mbedtls_ssl_set_hostname(&ssl, url.host.c_str())) != 0)
	{
		logTlsError("ssl setup failed", rc);
		return false;
	}
	mbedtls_ssl_set_bio(&ssl, &serverFd, mbedtls_net_send, mbedtls_net_recv, mbedtls_net_recv_timeout);

	if ((rc = mbedtls_net_connect(&serverFd, url.host.c_str(), url.port.c_str(),
	                              MBEDTLS_NET_PROTO_TCP)) != 0)
	{
		logTlsError("connect failed", rc);
		return false;
	}
	while ((rc = mbedtls_ssl_handshake(&ssl)) != 0)
	{
		if (rc != MBEDTLS_ERR_SSL_WANT_READ && rc != MBEDTLS_ERR_SSL_WANT_WRITE)
		{
			logTlsError("handshake failed", rc);
			return false;
		}
	}

	// Request head + body.
	std::string head;
	head += request.method;
	head += ' ';
	head += url.path;
	head += " HTTP/1.1\r\n";
	head += "Host: " + url.host + "\r\n";
	head += std::string("User-Agent: ") + kUserAgent + "\r\n";
	head += "Connection: close\r\n";
	for (const auto &header : request.headers)
		head += header.first + ": " + header.second + "\r\n";
	if (request.method == "POST")
		head += "Content-Length: " + std::to_string(request.body.size()) + "\r\n";
	head += "\r\n";
	head += request.body;

	std::size_t sent = 0;
	while (sent < head.size())
	{
		rc = mbedtls_ssl_write(&ssl,
		                       reinterpret_cast<const unsigned char *>(head.data() + sent),
		                       head.size() - sent);
		if (rc == MBEDTLS_ERR_SSL_WANT_READ || rc == MBEDTLS_ERR_SSL_WANT_WRITE)
			continue;
		if (rc <= 0)
		{
			logTlsError("write failed", rc);
			return false;
		}
		sent += static_cast<std::size_t>(rc);
	}

	// Connection: close means EOF delimits the body; the read loop also
	// stops on read timeouts (server closed without close_notify) -- the
	// parser is content-length agnostic there, same as curl's behavior.
	std::string raw;
	std::vector<unsigned char> chunk(16 * 1024);
	for (;;)
	{
		rc = mbedtls_ssl_read(&ssl, chunk.data(), chunk.size());
		if (rc == 0 || rc == MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY ||
		    rc == MBEDTLS_ERR_SSL_TIMEOUT || rc == MBEDTLS_ERR_NET_CONN_RESET)
			break;
		if (rc == MBEDTLS_ERR_SSL_WANT_READ || rc == MBEDTLS_ERR_SSL_WANT_WRITE)
			continue;
		if (rc < 0)
		{
			logTlsError("read failed", rc);
			return false;
		}
		if (raw.size() + static_cast<std::size_t>(rc) > kMaxResponseBytes)
		{
			MC_LOG_ERROR("auth", "pc: response over the size cap\n");
			return false;
		}
		raw.append(reinterpret_cast<const char *>(chunk.data()), static_cast<std::size_t>(rc));
	}

	return parseHttpResponse(raw, response.status, response.body);
}

#else // !PLATFORM_MSAUTH

bool PlatformAuth::microsoftLoginSupported()
{
	return false;
}

bool PlatformAuth::httpsRequest(const HttpRequest &request, HttpResponse &response)
{
	(void)request;
	(void)response;
	return false;
}

#endif // PLATFORM_MSAUTH
